### ISSUE TITLE
Error on placing BTC orders since there can at most be one digit after the decimal point

### ISSUE THREAD

**Issue by x-ji** [LabZoneSK/stop-loss-bot#9]
Thanks for the bot. Stop loss orders are really indispensable if one's to do day trading/swing trading. However, the bot doesn't seem to work with BTC on Kraken since the price information contains two digits after the decimal point but Kraken supports a precision of only one digit when placing the order. This results in an error saying that the order price is invalid. Would there be a quick way to fix that? Thanks.

**Comment by martin-starosta** [comment]
Thank you for creating this issue. I have added few changes to the code:
- precision for symbol can be set in config.js. For example:
```
{
        "symbol": "BTC",
        "kraken": "XXBT",
        "target": 4500,
        "precision": 1,
},
```
- if there is no precision for symbol, bot uses default precision which is set to 2 digits. Value can be changed in .env file

I will take a look for option to set precisions automatically. 

DO NOT FORGET TO UPDATE CODE ON YOUR LOCAL AND TEST BEFORE YOU RUN ON LIVE.

**Comment by x-ji** [comment]
Thanks for the very quick response. I've currently not triggered any stop loss orders so I cannot say whether it works on production now. But it seems good. In fact I've been holding some short positions so what I'd find also useful would be a stop loss in the reverse direction, i.e. orders with leverages. I understand that there might be a bit more of work to do on that and I myself might actually also look into implementing that if possible if I get time. Kraken doesn't seem to have any clear schedule on when they'd enable stop loss orders again so this sort of software would be really helpful to many traders.

**Comment by martin-starosta** [comment]
Sure, you are welcome. Could you explain in more detail feature you mentioned. You can explain here or drop me a note (my email is in readme). I can implement it later.

**Comment by x-ji** [comment]
Yeah maybe I can open another issue to explain it. Thank you very much.
